<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Core\Interfaces\" />
      <Folder Include="Tools\" />
      <Folder Include="Utils\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.8" />
      <PackageReference Include="Spectre.Console" Version="0.50.0" />
      <PackageReference Include="Spectre.Console.Analyzer" Version="1.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Spectre.Console.Cli" Version="0.50.0" />
      <PackageReference Include="Spectre.Console.ImageSharp" Version="0.50.0" />
      <PackageReference Include="Spectre.Console.Json" Version="0.50.0" />
      <PackageReference Include="Spectre.Console.Testing" Version="0.50.0" />
      <PackageReference Include="System.Text.Json" Version="9.0.4" />
    </ItemGroup>

</Project>
