name: .NET Build and Release

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore DaoKongLibrary.sln
      - name: Build
        run: dotnet build DaoKongLibrary.sln --no-restore
      - name: Test
        run: dotnet test DaoKongLibrary.sln --no-build --verbosity normal

  publish:
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Set Version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Restore dependencies
        run: dotnet restore DaoKongLibrary.sln

      - name: Build Library
        run: dotnet build DaoKong/DaoKong.csproj --configuration Release -p:Version=${{ env.VERSION }}

      - name: Pack NuGet package
        run: dotnet pack DaoKong/DaoKong.csproj --configuration Release -p:Version=${{ env.VERSION }} --no-build --output ./nupkgs

      - name: Upload NuGet Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DaoKong.${{ env.VERSION }}.nupkg
          path: ./nupkgs/*.nupkg

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./nupkgs/*.nupkg
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
